snake can no longer perform a 180 turn
terminal-based-games/ouroboros pull request #11
Opened 2019-07-30 19:42 UTC by mackkcooper

2019-07-30 20:38 UTC, carissaallen requested changes
This is a great improvement! It solves the issue of the snake making a 180 degree turn and the game abruptly exiting. 👍 

Since we currently have methods in the Snake class that handle the snake's movement (e.g., the method that allows the snake to move across an edge to the opposite side of the screen), I think we should move this method to the Snake class. 

Let me know if you agree, or if you think it makes sense to have methods handling the snake's movement in another class. I'm open to these methods living elsewhere, but I think they should be grouped together.

2019-07-30 21:20 UTC, mackkcooper commented
I totally agree! I think it makes sense to group these functions.

2019-08-03 05:41 UTC, carissaallen commented
Thanks for grouping the methods that relate to the snake's movement on the game board! I tested it out and it works perfectly. 👍

2019-08-03 05:41 UTC, carissaallen approved these changes

2019-08-03 05:43 UTC, merged